# db
spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/speaker_1?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 5
    maxActive: 20
    initialSize: 5
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    filters: stat,wall,logback

mybatis:
  mapper-locations: classpath*:mappers/*.xml

camel:
  springboot:
    main-run-controller: true
management:
  endpoint:
    camelroutes:
      enabled: true
      read-only: true

ftp:
  txt:
    url: 127.0.0.1:21
    name: test
    password: xxx
    dir: /txt_info
    server-info: ftp://${ftp.txt.url}/${ftp.txt.dir}?username=${ftp.txt.name}&password=${ftp.txt.password}&delay=5s&readLock=rename&filter=#ftpDownloadFileFilter&noop=true&recursive=true&passiveMode=true
    # 文件存放本地路径
    local-save-dir: D:/ftpdata/txt/save


db:
  insert:
    max:
      size: 3000
